name: 'Run Updock'
description: 'Run Updock over a series of repositories to upgrade docker images'
author: 'ItsVeryWindy'
branding:
  icon: play
  color: green
inputs:
  email:
    description: 'Email to use in the commit, will default to github actions email'
  updock-version:
    description: 'Version of updock to run against, will default to latest'
  github-token:
    description: 'GitHub token to run the search, access repositories and create the pull requests. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
  search:
    description: 'The GitHub search query to run, will default to the current repository'
  config:
    description: 'Inline configuration matching the up-dock format'
  dry-run:
    description: 'Run without creating pull requests'
    default: false
  authentication:
    description: 'Authentication for a repository, json string with the format { "repository.com": { "username": "username", "password": "password" } }'
  cache:
    description: 'Cache the results from this run to re-use in another'
    default: false
  report:
    description: 'Enables report output that can be piped into another action'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
